# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import server_pb2 as server__pb2


class SortServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DivideAndMerge = channel.unary_unary(
                '/SortService/DivideAndMerge',
                request_serializer=server__pb2.Array.SerializeToString,
                response_deserializer=server__pb2.Array.FromString,
                )
        self.SortArray = channel.unary_unary(
                '/SortService/SortArray',
                request_serializer=server__pb2.Array.SerializeToString,
                response_deserializer=server__pb2.Array.FromString,
                )


class SortServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DivideAndMerge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SortArray(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SortServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DivideAndMerge': grpc.unary_unary_rpc_method_handler(
                    servicer.DivideAndMerge,
                    request_deserializer=server__pb2.Array.FromString,
                    response_serializer=server__pb2.Array.SerializeToString,
            ),
            'SortArray': grpc.unary_unary_rpc_method_handler(
                    servicer.SortArray,
                    request_deserializer=server__pb2.Array.FromString,
                    response_serializer=server__pb2.Array.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SortService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SortService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DivideAndMerge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SortService/DivideAndMerge',
            server__pb2.Array.SerializeToString,
            server__pb2.Array.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SortArray(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SortService/SortArray',
            server__pb2.Array.SerializeToString,
            server__pb2.Array.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
