# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cserver.proto\"\x15\n\x05\x41rray\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\x05\x32P\n\x0bSortService\x12\"\n\x0e\x44ivideAndMerge\x12\x06.Array\x1a\x06.Array\"\x00\x12\x1d\n\tSortArray\x12\x06.Array\x1a\x06.Array\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ARRAY']._serialized_start=16
  _globals['_ARRAY']._serialized_end=37
  _globals['_SORTSERVICE']._serialized_start=39
  _globals['_SORTSERVICE']._serialized_end=119
# @@protoc_insertion_point(module_scope)
